# Generated by Django 4.0.2 on 2022-02-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_age_customuser_avatar_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='f_name',
            field=models.CharField(default='name', max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='l_name',
            field=models.CharField(default='name', max_length=50, verbose_name='Фамилия'),
        ),
    ]
