# Generated by Django 4.0.2 on 2022-02-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_f_name_customuser_l_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='f_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='l_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
